language: python

python:
  - "2.7"
  - "3.4"

sudo: false

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create --yes -q -n test python=$TRAVIS_PYTHON_VERSION pip numpy matplotlib pytest
  - source activate test
  - pip install .

script:
  - py.test